version: "3.4"
services:
  db:
    image: 'mysql:5.7'
    env_file:
      - .env
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
    ports:
      - '3306:3306'
    volumes:
      - 'db_data:/var/lib/mysql'
      - '.:/app'

  app:
    build:
      context: .
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    depends_on:
      - db
    links:
      - db

volumes:
  db_data:
  web_rubygems: